// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Recipe struct {
	ID          int64
	Name        string
	Description sql.NullString
	Color       sql.NullString
	Yield       sql.NullString
	ActiveTime  sql.NullString
	TotalTime   sql.NullString
}

type RecipeIngredient struct {
	ID           int64
	RecipeID     int64
	IngredientID int64
}

type RecipeStep struct {
	ID             int64
	RecipeID       int64
	SequenceNumber int64
}
